# Custom Language File for Launcher Customizer

[ejs.app]
title = "PinkyCore Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Luca-Caporaloni"
mediaTwitterURL = "#"
mediaInstagramURL = "https://www.instagram.com/pinkythedoggames/"
mediaYouTubeURL = "https://www.youtube.com/@Pinky_Games"
mediaDiscordURL = "https://discord.gg/TBVbbQuPbr"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "WELCOME TO PINKYCORE LAUNCHER"
welcomeDescription = ""
welcomeDescCTA = ""
